name: FoPzlHoppers
main: me.fopzl.hoppers.FoPzlHoppers
author: FoPzl
depend: 
  - NeoCore
  - NBTAPI
version: "0.1"
api: "1.19"
commands:
   fopzlhoppers:
      aliases: [fhop]
      permission: fopzlhoppers.admin
permissions:
   fopzlhoppers.admin:
      default: false
