name: FoPzlHoppers
main: me.fopzl.hoppers.FoPzlHoppers
author: FoPzl
depend: [NBTAPI]
version: 0.1
api-version: 1.19
commands:
   fopzlhoppers:
      aliases: [fhop]
permissions:
   fopzlhoppers.admin:
      default: false
